version: '3.8'
services: 
  crop-gpt-bot:
   container_name: gpt-bot
   image: ghcr.io/baiyz0825/corp-wechat-gptbot:main
   ports:
    - "50008":"50008"
   volumes:
    - /home/byz/gpt/config:/apps/config:rw 
    - /home/byz/gpt/db:/apps/db:rw 
    - /home/byz/gpt/logs:/apps/logs:rw     
   deploy:         
    restart_policy:
      condition: on-failure
      delay: 5s
      max_attempts: 3
      window: 120s     
   restart: always
   networks:
     - host
