systemConf:
  proxy: http://192.168.0.44:7890 # http代理地址
  port: 50008 # 允许端口
  log: debug # panic, fatal, error, warn, info, debug, trace
  logPath: ./logs/log #日志文件位置
  callBackUrl: http://127.0.0.1 # 回调地址
  msgMode: text # markdown 或者 text
gptConfig:
  apikey: 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 # openapi key
  model: gpt-3.5-turbo # 对话模型
  UserName: jgwecbaap # 用户名
  url: https://api.openai.com/v1 # 请求基地址
  contextNumber: 10 #支持的上下文数量
  contextExpireTime: 10 #上下文存储时间
weConfig:
  corpid: ww0bec1a3850fbe507 # 企业id
  corpSecret: XC5l4D-fxgLuUeyqGlNH9gOvBjucQOWN_DCyOi04CMc #应用密码
  agentId: 1000002 # 应用Id
  weApiRCallToken: Qp7QDRJjo # 调用token
  weApiEncodingKey: CpRx0XF1QEi1z4aBjSctb3d399p8EInliVfMQ3dSWvN # jiami
  weChatApiAddr:  https://qyapi.weixin.qq.com # 企业微信推送api地址