name: 测试

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
on:
  # 手动触发事件
  workflow_dispatch:


jobs:
  installAndCheckDockerEnv:
    runs-on: ubuntu-latest
 
    steps:
    - name: 检查Docker是否安装
      id: check-docker
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_SSH_USERNAME }}
        password: ${{ secrets.VPS_SSH_PASSWD }}
        port: ${{ secrets.VPS_SSH_PORT}}
        script: |
          if command -v docker > /dev/null 2>&1; then
            echo "Docker is already installed on the remote server"
            echo "::set-output name=installed::true"
          else
            echo "Docker is not installed on the remote server"
            echo "::set-output name=installed::false"
          fi        
    - name: 安装Docker
      id: install-docker
      if: steps.check-docker.outputs.installed == false
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_SSH_USERNAME }}
        password: ${{ secrets.VPS_SSH_PASSWD }}
        port: ${{ secrets.VPS_SSH_PORT}}
        script: |
          echo "${{ steps.check-docker.outputs.installed }}"
